# Generated by Django 3.2.9 on 2021-11-04 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Setup', '0002_alter_clientes_observacion'),
        ('Depilacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depilacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_tipo', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1, max_length=2)),
                ('fecha', models.DateTimeField()),
                ('Cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Setup.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Depilacion_zonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Potencia', models.IntegerField()),
                ('Depilacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Depilacion.depilacion')),
                ('Zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Depilacion.zonas')),
            ],
            options={
                'verbose_name': 'Zonas',
                'verbose_name_plural': 'Zonas',
            },
        ),
    ]
