# Generated by Django 3.2.9 on 2021-11-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depilacion', '0002_depilacion_depilacion_zonas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depilacion',
            name='foto_tipo',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=1, max_length=1),
        ),
    ]
