# Generated by Django 3.2.9 on 2021-11-06 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Setup', '0003_staff'),
        ('Depilacion', '0004_depilacion_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_reserva', models.DateTimeField()),
                ('Cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Setup.clientes')),
            ],
        ),
    ]
