# Generated by Django 3.2.9 on 2021-11-06 01:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Depilacion', '0005_reservas'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='Hora_reserva',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservas',
            name='Fecha_reserva',
            field=models.DateField(),
        ),
    ]
