# Generated by Django 3.2.9 on 2021-11-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=30)),
                ('Telefono', models.CharField(max_length=20)),
                ('Direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('Cuil', models.CharField(blank=True, max_length=20, null=True)),
                ('Cumpleanos', models.DateField(blank=True, null=True)),
                ('Activa', models.BooleanField(default=False)),
                ('Observacion', models.TextField(max_length=140)),
            ],
            options={
                'verbose_name': 'Clientes',
                'verbose_name_plural': 'Clientes',
                'ordering': ['Apellido'],
            },
        ),
    ]
