# Generated by Django 3.2.9 on 2021-11-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Observacion',
            field=models.TextField(blank=True, max_length=140, null=True),
        ),
    ]
